using Newtonsoft.Json;
using QRMS.AppLIB.Common;
using QRMS.Helper;
using PropertyChanged;
using System;
using System.Collections.Generic;
using System.Text;

namespace QRMS.Models
{
    public partial class CartedContractAlterModel : Notifiable
    {        
        public int ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public int CUSTOMER_ID_CHANGE { get; set; }
        public string CUST_TYPE { get; set; }
        public int CUST_TYPE_CHANGE { get; set; }
        public string CUST_NAME { get; set; }
        public int CUST_NAME_CHANGE { get; set; }
        public string IDENTITY_NO { get; set; }
        public int IDENTITY_NO_CHANGE { get; set; }
        public string CUST_PHONE { get; set; }
        public int CUST_PHONE_CHANGE { get; set; }
        public string CUST_EMAIL { get; set; }
        public int CUST_EMAIL_CHANGE { get; set; }
        public string CUST_ADDRESS { get; set; }
        public int CUST_ADDRESS_CHANGE { get; set; }
        public Nullable<int> CUST_COUNTRY_ID { get; set; }
        public int CUST_COUNTRY_ID_CHANGE { get; set; }
        public string CUST_COUNTRY_NAME { get; set; }
        public Nullable<int> CUST_PROVINCE_ID { get; set; }
        public int CUST_PROVINCE_ID_CHANGE { get; set; }
        public string CUST_PROVINCE_NAME { get; set; }
        public Nullable<int> CUST_DISTRICT_ID { get; set; }
        public int CUST_DISTRICT_ID_CHANGE { get; set; }
        public string CUST_DISTRICT_NAME { get; set; }
        public Nullable<int> CUS_WARD_ID { get; set; }
        public int CUS_WARD_ID_CHANGE { get; set; }
        public string CUST_WARD_NAME { get; set; }
        public string BEN_NAME { get; set; }
        public int BEN_NAME_CHANGE { get; set; }
        public string BEN_IDENTITY_ID { get; set; }
        public int BEN_IDENTITY_ID_CHANGE { get; set; }
        public string BEN_PHONE { get; set; }
        public int BEN_PHONE_CHANGE { get; set; }
        public string VEH_PLATE_NO { get; set; }
        public int VEH_PLATE_NO_CHANGE { get; set; }
        public string VEH_FRAME_NO { get; set; }
        public int VEH_FRAME_NO_CHANGE { get; set; }
        public string VEH_ENGINE_NO { get; set; }
        public int VEH_ENGINE_NO_CHANGE { get; set; }
        public Nullable<int> VEH_BRAND_ID { get; set; }
        public int VEH_BRAND_ID_CHANGE { get; set; }
        public string VEH_BRAND_NAME { get; set; }
        public Nullable<int> VEH_MODEL_ID { get; set; }
        public int VEH_MODEL_ID_CHANGE { get; set; }
        public string VEH_MODEL_NAME { get; set; }
        public Nullable<int> VEH_TYPE_ID { get; set; }
        public int VEH_TYPE_ID_CHANGE { get; set; }
        public string VEH_TYPE_NAME { get; set; }
        public Nullable<decimal> VEH_CUBE_CAPACITY { get; set; }
        public int VEH_CUBE_CAPACITY_CHANGE { get; set; }
        public Nullable<decimal> VEH_MAX_LOAD { get; set; }
        public int VEH_MAX_LOAD_CHANGE { get; set; }
        public Nullable<short> VEH_SEAT_NO { get; set; }
        public int VEH_SEAT_NO_CHANGE { get; set; }
        public Nullable<int> VEH_ORIGIN { get; set; }
        public int VEH_ORIGIN_CHANGE { get; set; }
        public string VEH_ORIGIN_NAME { get; set; }
        public Nullable<System.DateTime> VEH_FIRST_REG_DATE { get; set; }
        public int VEH_FIRST_REG_DATE_CHANGE { get; set; }
        public Nullable<int> VEH_PURPOSE_ID { get; set; }
        public int VEH_PURPOSE_ID_CHANGE { get; set; }
        public string VEH_PURPOSE { get; set; }
        public Nullable<decimal> VEH_VALUE { get; set; }
        public int VEH_VALUE_CHANGE { get; set; }
        public Nullable<int> SALE_ACCOUNT_ID { get; set; }
        public Nullable<int> SALE_ACCOUNT_ID_CHANGE { get; set; }
        public Nullable<int> CUST_ACCOUNT_ID { get; set; }
        public Nullable<int> CUST_ACCOUNT_ID_CHANGE { get; set; }
        public string SALE_PERSONEL_CODE { get; set; }
        public int SALE_PERSONEL_CODE_CHANGE { get; set; }
        public string CONTRACT_CERT_NO { get; set; }
        public int CONTRACT_CERT_NO_CHANGE { get; set; }
        public string CONTRACT_PRINT_NO { get; set; }
        public int CONTRACT_PRINT_NO_CHANGE { get; set; }
        public Nullable<System.DateTime> CONTRACT_ISSUED_DATE { get; set; }
        public int CONTRACT_ISSUED_DATE_CHANGE { get; set; }
        public Nullable<System.DateTime> CONTRACT_START_DATE { get; set; }
        public int CONTRACT_START_DATE_CHANGE { get; set; }
        public Nullable<System.DateTime> CONTRACT_EXPIRE_DATE { get; set; }
        public int CONTRACT_EXPIRE_DATE_CHANGE { get; set; }
        public string CONTRACT_ISSUE_TYPE { get; set; }
        public int CONTRACT_ISSUE_TYPE_CHANGE { get; set; }
        public Nullable<decimal> INSURED_TOTAL_VAL { get; set; }
        public int INSURED_TOTAL_VAL_CHANGE { get; set; }
        public Nullable<decimal> DEDUCT_TOTAL_VAL { get; set; }
        public int DEDUCT_TOTAL_VAL_CHANGE { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public int TOTAL_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TOTAL_DEDUCT_PRICE { get; set; }
        public int TOTAL_DEDUCT_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TOTAL_DEDUCT_RATIO { get; set; }
        public int TOTAL_DEDUCT_RATIO_CHANGE { get; set; }
        public Nullable<float> TOTAL_VAT { get; set; }
        public int TOTAL_VAT_CHANGE { get; set; }
        public Nullable<int> PAY_METHOD { get; set; }
        public int PAY_METHOD_CHANGE { get; set; }
        public Nullable<System.DateTime> PAY_DUE_DATE { get; set; }
        public int PAY_DUE_DATE_CHANGE { get; set; }
        public Nullable<decimal> TNDSBB_AUTO_PRICE { get; set; }
        public int TNDSBB_AUTO_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNDSBB_AUTO_DE_PRICE { get; set; }
        public int TNDSBB_AUTO_DE_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNSDBB_AUTO_VAT { get; set; }
        public int TNSDBB_AUTO_VAT_CHANGE { get; set; }
        public Nullable<decimal> TNDSBB_MOTO_PRICE { get; set; }
        public int TNDSBB_MOTO_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNDSBB_MOTO_DE_PRICE { get; set; }
        public int TNDSBB_MOTO_DE_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNDSBB_MOTO_VAT { get; set; }
        public int TNDSBB_MOTO_VAT_CHANGE { get; set; }
        public Nullable<short> TNVN_AUTO_CREW_NO { get; set; }
        public int TNVN_AUTO_CREW_NO_CHANGE { get; set; }
        public Nullable<int> TNVN_AUTO_CREW_PCLAIM_ID { get; set; }
        public int TNVN_AUTO_CREW_PCLAIM_ID_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_CREW_PCLAIM { get; set; }
        public int TNVN_AUTO_CREW_PCLAIM_CHANGE { get; set; }
        public Nullable<short> TNVN_AUTO_PSGR_NO { get; set; }
        public int TNVN_AUTO_PSGR_NO_CHANGE { get; set; }
        public Nullable<int> TNVN_AUTO_PSGR_PCLAIM_ID { get; set; }
        public int TNVN_AUTO_PSGR_PCLAIM_ID_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_PSGR_PCLAIM { get; set; }
        public int TNVN_AUTO_PSGR_PCLAIM_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_PRICE { get; set; }
        public int TNVN_AUTO_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_DE_PRICE { get; set; }
        public int TNVN_AUTO_DE_PRICE_CHANGE { get; set; }
        public Nullable<float> TNVN_AUTO_DE_RATIO { get; set; }
        public int TNVN_AUTO_DE_RATIO_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_VAT { get; set; }
        public int TNVN_AUTO_VAT_CHANGE { get; set; }
        public Nullable<int> TNDSTN_ADD_AUTO_TYPE { get; set; }
        public int TNDSTN_ADD_AUTO_TYPE_CHANGE { get; set; }
        public Nullable<int> TNDSTN_ADD_AUTO_PCLAIM_ID { get; set; }
        public int TNDSTN_ADD_AUTO_PCLAIM_ID_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_ASSEST { get; set; }
        public int TNDSTN_ADD_AUTO_ASSEST_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_CREW { get; set; }
        public int TNDSTN_ADD_AUTO_CREW_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_PRICE { get; set; }
        public int TNDSTN_ADD_AUTO_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_DE_PRICE { get; set; }
        public int TNDSTN_ADD_AUTO_DE_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_VAT { get; set; }
        public int TNDSTN_ADD_AUTO_VAT_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_PSGR { get; set; }
        public int TNDSTN_ADD_AUTO_PSGR_CHANGE { get; set; }
        public Nullable<int> TNDS_AUTO_LOAD_TYPE { get; set; }
        public int TNDS_AUTO_LOAD_TYPE_CHANGE { get; set; }
        public string TNDS_AUTO_LOAD_TYPE_NAME { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_LMT { get; set; }
        public int TNDS_AUTO_LOAD_LMT_CHANGE { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_DEDUCT { get; set; }
        public int TNDS_AUTO_LOAD_DEDUCT_CHANGE { get; set; }
        public string TNDS_AUTO_LOAD_OWN { get; set; }
        public int TNDS_AUTO_LOAD_OWN_CHANGE { get; set; }
        public int TNDS_AUTO_LOAD_OWN_CHANGE_STATUS { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_PRICE { get; set; }
        public int TNDS_AUTO_LOAD_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_DE_PRICE { get; set; }
        public int TNDS_AUTO_LOAD_DE_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_VAT { get; set; }
        public int TNDS_AUTO_LOAD_VAT_CHANGE { get; set; }
        public Nullable<decimal> VC_AUTO_VEH_VALUE { get; set; }
        public int VC_AUTO_VEH_VALUE_CHANGE { get; set; }
        public Nullable<decimal> VS_AUTO_INSURE_VAL { get; set; }
        public int VS_AUTO_INSURE_VAL_CHANGE { get; set; }
        public Nullable<decimal> VC_AUTO_DE_PRICE { get; set; }
        public int VC_AUTO_DE_PRICE_CHANGE { get; set; }
        public Nullable<decimal> VC_AUTO_DE_PRICE_RATIO { get; set; }
        public int VC_AUTO_DE_PRICE_RATIO_CHANGE { get; set; }
        public Nullable<decimal> VC_AUTO_PRICE { get; set; }
        public int VC_AUTO_PRICE_CHANGE { get; set; }
        public Nullable<decimal> VC_AUTO_VAT { get; set; }
        public int VC_AUTO_VAT_CHANGE { get; set; }
        public Nullable<int> TNVN_MOTO_PCLAIM_ID { get; set; }
        public int TNVN_MOTO_PCLAIM_ID_CHANGE { get; set; }
        public Nullable<decimal> TNVN_MOTO_PCLAIM { get; set; }
        public int TNVN_MOTO_PCLAIM_CHANGE { get; set; }
        public Nullable<decimal> TNVN_MOTO_PRICE { get; set; }
        public int TNVN_MOTO_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNVN_MOTO_DE_PRICE { get; set; }
        public int TNVN_MOTO_DE_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNVN_MOTO_VAT { get; set; }
        public int TNVN_MOTO_VAT_CHANGE { get; set; }
        public Nullable<decimal> VC_MOTO_VEH_VALUE { get; set; }
        public int VC_MOTO_VEH_VALUE_CHANGE { get; set; }
        public Nullable<decimal> VC_MOTO_INSURE_VAL { get; set; }
        public int VC_MOTO_INSURE_VAL_CHANGE { get; set; }
        public Nullable<decimal> VC_MOTO_CLAIM_DEDUCT { get; set; }
        public int VC_MOTO_CLAIM_DEDUCT_CHANGE { get; set; }
        public Nullable<decimal> VC_AUTO_CLAIM_DEDUCT { get; set; }
        public int VC_AUTO_CLAIM_DEDUCT_CHANGE { get; set; }
        public Nullable<decimal> VC_MOTO_PRICE { get; set; }
        public int VC_MOTO_PRICE_CHANGE { get; set; }
        public Nullable<decimal> VC_MOTO_DE_PRICE { get; set; }
        public int VC_MOTO_DE_PRICE_CHANGE { get; set; }
        public Nullable<decimal> VC_MOTO_DE_RATIO { get; set; }
        public int VC_MOTO_DE_RATIO_CHANGE { get; set; }
        public Nullable<decimal> VC_MOTO_VAT { get; set; }
        public int VC_MOTO_VAT_CHANGE { get; set; }
        public string STATUS_RECORD { get; set; }
        public Nullable<int> TNDSTN_ADD_MOTO_TYPE { get; set; }
        public int TNDSTN_ADD_MOTO_TYPE_CHANGE { get; set; }
        public Nullable<int> TNDSTN_ADD_MOTO_PCLAIM_ID { get; set; }
        public int TNDSTN_ADD_MOTO_PCLAIM_ID_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_MOTO_ASSEST { get; set; }
        public int TNDSTN_ADD_MOTO_ASSEST_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_MOTO_CREW { get; set; }
        public int TNDSTN_ADD_MOTO_CREW_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_MOTO_PSGR { get; set; }
        public int TNDSTN_ADD_MOTO_PSGR_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_PRICE { get; set; }
        public int TNDSTN_ADD_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_DE_PRICE { get; set; }
        public int TNDSTN_ADD_DE_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_VAT { get; set; }
        public int TNDSTN_ADD_VAT_CHANGE { get; set; }
        public Nullable<int> INPUTING_USER_ID { get; set; }
        public int INPUTING_USER_ID_CHANGE { get; set; }
        public string BILL_NAME { get; set; }
        public int BILL_NAME_CHANGE { get; set; }
        public string BILL_IDENTITY_NO { get; set; }
        public int BILL_IDENTITY_NO_CHANGE { get; set; }
        public Nullable<int> BILL_COUNTRY_ID { get; set; }
        public int BILL_COUNTRY_ID_CHANGE { get; set; }
        public string BILL_COUNTRY_NAME { get; set; }
        public Nullable<int> BILL_PROVINCE_ID { get; set; }
        public int BILL_PROVINCE_ID_CHANGE { get; set; }
        public string BILL_PROVINCE_NAME { get; set; }
        public Nullable<int> BILL_DISTRICT_ID { get; set; }
        public int BILL_DISTRICT_ID_CHANGE { get; set; }
        public string BILL_DISTRICT_NAME { get; set; }
        public Nullable<int> BILL_WARD_ID { get; set; }
        public int BILL_WARD_ID_CHANGE { get; set; }
        public string BILL_WARD_NAME { get; set; }
        public string BILL_ADDRESS { get; set; }
        public int BILL_ADDRESS_CHANGE { get; set; }
        public Nullable<int> CONTRACT_STATUS { get; set; }
        public int CONTRACT_STATUS_CHANGE { get; set; }
        public string CONTRACT_STATUS_NAME { get; set; }
        public string BILL_IDENTITY_TYPE { get; set; }
        public int BILL_IDENTITY_TYPE_CHANGE { get; set; }
        public string IDENTITY_TYPE { get; set; }
        public int IDENTITY_TYPE_CHANGE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public int DISCOUNT_CHANGE { get; set; }
        public Nullable<int> DISCOUNT_PROG_ID { get; set; }
        public int DISCOUNT_PROG_ID_CHANGE { get; set; }
        public string DISCOUNT_PROG_NAME { get; set; }
        public int DISCOUNT_PROG_NAME_CHANGE { get; set; }
        public Nullable<decimal> DISCOUNT_RATIO { get; set; }
        public int DISCOUNT_RATIO_CHANGE { get; set; }
        public string TAX_NO { get; set; }
        public int TAX_NO_CHANGE { get; set; }
        public string CONTRACT_CODE { get; set; }
        public int CONTRACT_CODE_CHANGE { get; set; }
        public Nullable<int> AGENT_ID { get; set; }
        public int AGENT_ID_CHANGE { get; set; }
        public string AGENT_NAME { get; set; }
        public int AGENT_NAME_CHANGE { get; set; }
        public Nullable<int> INSUR_PRODUCT_ID { get; set; }
        public int INSUR_PRODUCT_ID_CHANGE { get; set; }
        public string INSUR_PRODUCT_CODE { get; set; }
        public int INSUR_PRODUCT_CODE_CHANGE { get; set; }
        public string INSUR_PRODUCT_NAME { get; set; }
        public int INSUR_PRODUCT_NAME_CHANGE { get; set; }
        public string AGENT_CODE { get; set; }
        public int AGENT_CODE_CHANGE { get; set; }
        public Nullable<int> APPROVAL_AGENT_ID { get; set; }
        public int APPROVAL_AGENT_ID_CHANGE { get; set; }
        public string APPROVAL_AGENT_CODE { get; set; }
        public int APPROVAL_AGENT_CODE_CHANGE { get; set; }
        public string APPROVAL_AGENT_NAME { get; set; }
        public int APPROVAL_AGENT_NAME_CHANGE { get; set; }
        public Nullable<int> DIVN_ID { get; set; }
        public int DIVN_ID_CHANGE { get; set; }
        public string DIVN_CODE { get; set; }
        public int DIVN_CODE_CHANGE { get; set; }
        public string DIVN_NAME { get; set; }
        public int DIVN_NAME_CHANGE { get; set; }
        public Nullable<int> AGENT_ID_C_1 { get; set; }
        public int AGENT_ID_C_1_CHANGE { get; set; }
        public Nullable<int> AGENT_ID_C_2 { get; set; }
        public int AGENT_ID_C_2_CHANGE { get; set; }
        public Nullable<int> AGENT_ID_C_3 { get; set; }
        public int AGENT_ID_C_3_CHANGE { get; set; }
        public Nullable<int> AGENT_ID_C_4 { get; set; }
        public int AGENT_ID_C_4_CHANGE { get; set; }
        public Nullable<int> AGENT_ID_C_5 { get; set; }
        public int AGENT_ID_C_5_CHANGE { get; set; }
        public Nullable<int> AGENT_ID_C_6 { get; set; }
        public int AGENT_ID_C_6_CHANGE { get; set; }
        public Nullable<int> AGENT_ID_C_7 { get; set; }
        public int AGENT_ID_C_7_CHANGE { get; set; }
        public Nullable<int> AGENT_ID_C_8 { get; set; }
        public int AGENT_ID_C_8_CHANGE { get; set; }
        public Nullable<int> AGENT_ID_C_9 { get; set; }
        public int AGENT_ID_C_9_CHANGE { get; set; }
        public Nullable<int> AGENT_ID_C_10 { get; set; }
        public int AGENT_ID_C_10_CHANGE { get; set; }
        public string SALE_ACCOUNT_CODE { get; set; }
        public int SALE_ACCOUNT_CODE_CHANGE { get; set; }
        public string SALE_ACCOUNT_NAME { get; set; }
        public int SALE_ACCOUNT_NAME_CHANGE { get; set; }
        public string CUST_SEX { get; set; }
        public int CUST_SEX_CHANGE { get; set; }
        public string CUST_COUNTRY_CODE { get; set; }
        public int CUST_COUNTRY_CODE_CHANGE { get; set; }
        public string CUST_PROVINCE_CODE { get; set; }
        public int CUST_PROVINCE_CODE_CHANGE { get; set; }
        public string CUST_DISTRICT_CODE { get; set; }
        public int CUST_DISTRICT_CODE_CHANGE { get; set; }
        public string CUS_WARD_CODE { get; set; }
        public int CUS_WARD_CODE_CHANGE { get; set; }
        public string VEH_BRAND_CODE { get; set; }
        public int VEH_BRAND_CODE_CHANGE { get; set; }
        public string VEH_MODEL_CODE { get; set; }
        public int VEH_MODEL_CODE_CHANGE { get; set; }
        public string VEH_TYPE_CODE { get; set; }
        public int VEH_TYPE_CODE_CHANGE { get; set; }
        public string CONTRACT_PARENTS { get; set; }
        public int CONTRACT_PARENTS_CHANGE { get; set; }
        public string BILL_COMPANY { get; set; }
        public int BILL_COMPANY_CHANGE { get; set; }
        public string BILL_TAXNO { get; set; }
        public int BILL_TAXNO_CHANGE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_PCLAIM { get; set; }
        public int TNDSTN_ADD_AUTO_PCLAIM_CHANGE { get; set; }
        public Nullable<decimal> LOAD_WEIGHT { get; set; }
        public int LOAD_WEIGHT_CHANGE { get; set; }
        public Nullable<int> TNDS_AUTO_LOAD_LVL_ID { get; set; }
        public int TNDS_AUTO_LOAD_LVL_ID_CHANGE { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_PTON { get; set; }
        public int TNDS_AUTO_LOAD_PTON_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_CREW_PRICE { get; set; }
        public int TNVN_AUTO_CREW_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_CREW_DE_PRICE { get; set; }
        public int TNVN_AUTO_CREW_DE_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_CREW_VAT { get; set; }
        public int TNVN_AUTO_CREW_VAT_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_PSGR_PRICE { get; set; }
        public int TNVN_AUTO_PSGR_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_PSGR_DE_PRICE { get; set; }
        public int TNVN_AUTO_PSGR_DE_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TNVN_AUTO_PSGR_VAT { get; set; }
        public int TNVN_AUTO_PSGR_VAT_CHANGE { get; set; }
        public string CONTRACT_STATUS_CODE { get; set; }
        public int CONTRACT_STATUS_CODE_CHANGE { get; set; }
        public Nullable<decimal> TOTAL_ALTERED_PRICE { get; set; }
        public int TOTAL_ALTERED_PRICE_CHANGE { get; set; }
        public Nullable<decimal> TOTAL_FINAL_PRICE { get; set; }
        public int TOTAL_FINAL_PRICE_CHANGE { get; set; }
        public Nullable<short> ALTER_STATUS { get; set; }
        public Nullable<short> ALTER_TIMES { get; set; }
        public string REMARK { get; set; }
        public string BEN_ADDRESS { get; set; }
        public int BEN_ADDRESS_CHANGE { get; set; }
        public string BILL_COMPANY_ADDRESS { get; set; }
        public int BILL_COMPANY_ADDRESS_CHANGE { get; set; }
        public string REPRESENTATIVE_NAME { get; set; }
        public int REPRESENTATIVE_NAME_CHANGE { get; set; }
        public string VEHICLE_TYPE_NAME { get; set; }
        public int VEHICLE_TYPE_NAME_CHANGE { get; set; }
        public string VEHICLE_TYPE_REMARK { get; set; }
        public int VEHICLE_TYPE_REMARK_CHANGE { get; set; }
        public List<InsuranceContractDKBSModel> OLD_DKBS_LIST { get; set; }
        public List<CartedContractDKBSModel> NEW_DKBS_LIST { get; set; }
    }

    public partial class CartedContractAlterModel
    {
        public bool IsShowAllInformation { get; set; } = true;
    }
}
