using Newtonsoft.Json;
using QRMS.AppLIB.Common;
using QRMS.Helper;
using QRMS.Resources;
using PropertyChanged;
using System;
using System.Collections.Generic;

namespace QRMS.Models
{
    public partial class ContractAlterHistory : Notifiable
    {
        public int ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> ORIGINAL_ID { get; set; }
        public Nullable<int> CONTRACT_ID { get; set; }
        public Nullable<int> OLD_CUSTOMER_ID { get; set; }
        public Nullable<int> OLD_CUST_ACCOUNT_ID { get; set; }
        public string OLD_CUST_TYPE { get; set; }
        public string OLD_CUST_NAME { get; set; }
        public string OLD_IDENTITY_NO { get; set; }
        public string OLD_CUST_PHONE { get; set; }
        public string OLD_CUST_EMAIL { get; set; }
        public string OLD_CUST_ADDRESS { get; set; }
        public Nullable<int> OLD_CUST_COUNTRY_ID { get; set; }
        public Nullable<int> OLD_CUST_PROVINCE_ID { get; set; }
        public Nullable<int> OLD_CUST_DISTRICT_ID { get; set; }
        public Nullable<int> OLD_CUS_WARD_ID { get; set; }
        public string OLD_BEN_NAME { get; set; }
        public string OLD_BEN_IDENTITY_ID { get; set; }
        public string OLD_BEN_PHONE { get; set; }
        public Nullable<int> OLD_INPUTING_USER_ID { get; set; }
        public Nullable<int> OLD_CONTRACT_STATUS { get; set; }
        public string OLD_BILL_NAME { get; set; }
        public string OLD_BILL_IDENTITY_NO { get; set; }
        public string OLD_BILL_IDENTITY_TYPE { get; set; }
        public Nullable<int> OLD_BILL_COUNTRY_ID { get; set; }
        public Nullable<int> OLD_BILL_PROVINCE_ID { get; set; }
        public Nullable<int> OLD_BILL_DISTRICT_ID { get; set; }
        public Nullable<int> OLD_BILL_WARD_ID { get; set; }
        public string OLD_BILL_ADDRESS { get; set; }
        public string OLD_VEH_PLATE_NO { get; set; }
        public string OLD_VEH_FRAME_NO { get; set; }
        public string OLD_VEH_ENGINE_NO { get; set; }
        public Nullable<int> OLD_VEH_BRAND_ID { get; set; }
        public Nullable<int> OLD_VEH_MODEL_ID { get; set; }
        public Nullable<int> OLD_VEH_TYPE_ID { get; set; }
        public Nullable<decimal> OLD_VEH_CUBE_CAPACITY { get; set; }
        public Nullable<decimal> OLD_VEH_MAX_LOAD { get; set; }
        public Nullable<short> OLD_VEH_SEAT_NO { get; set; }
        public Nullable<int> OLD_VEH_ORIGIN { get; set; }
        public Nullable<System.DateTime> OLD_VEH_FIRST_REG_DATE { get; set; }
        public Nullable<int> OLD_VEH_PURPOSE_ID { get; set; }
        public Nullable<decimal> OLD_VEH_VALUE { get; set; }
        public Nullable<int> OLD_SALE_AGENT_ID { get; set; }
        public string OLD_SALE_AGENT_CODE { get; set; }
        public Nullable<int> OLD_SALE_ACCOUNT_ID { get; set; }
        public string OLD_SALE_PERSONEL_CODE { get; set; }
        public string OLD_CONTRACT_CERT_NO { get; set; }
        public string OLD_CONTRACT_PRINT_NO { get; set; }
        public Nullable<System.DateTime> OLD_CONTRACT_ISSUED_DATE { get; set; }
        public Nullable<System.DateTime> OLD_CONTRACT_START_DATE { get; set; }
        public Nullable<System.DateTime> OLD_CONTRACT_EXPIRE_DATE { get; set; }
        public string OLD_CONTRACT_ISSUE_TYPE { get; set; }
        public Nullable<decimal> OLD_INSURED_TOTAL_VAL { get; set; }
        public Nullable<decimal> OLD_DEDUCT_TOTAL_VAL { get; set; }
        public Nullable<decimal> OLD_TOTAL_PRICE { get; set; }
        public Nullable<decimal> OLD_TOTAL_DEDUCT_PRICE { get; set; }
        public Nullable<decimal> OLD_TOTAL_DEDUCT_RATIO { get; set; }
        public string OLD_IDENTITY_TYPE { get; set; }
        public Nullable<decimal> OLD_DISCOUNT { get; set; }
        public Nullable<int> OLD_DISCOUNT_PROG_ID { get; set; }
        public string OLD_DISCOUNT_PROG_NAME { get; set; }
        public Nullable<decimal> OLD_DISCOUNT_RATIO { get; set; }
        public Nullable<float> OLD_TOTAL_VAT { get; set; }
        public Nullable<int> OLD_PAY_METHOD { get; set; }
        public Nullable<System.DateTime> OLD_PAY_DUE_DATE { get; set; }
        public Nullable<decimal> OLD_TNDSBB_AUTO_PRICE { get; set; }
        public Nullable<decimal> OLD_TNDSBB_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_TNSDBB_AUTO_VAT { get; set; }
        public Nullable<decimal> OLD_TNDSBB_MOTO_PRICE { get; set; }
        public Nullable<decimal> OLD_TNDSBB_MOTO_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_TNDSBB_MOTO_VAT { get; set; }
        public Nullable<short> OLD_TNVN_AUTO_CREW_NO { get; set; }
        public Nullable<int> OLD_TNVN_AUTO_CREW_PCLAIM_ID { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_CREW_PCLAIM { get; set; }
        public Nullable<short> OLD_TNVN_AUTO_PSGR_NO { get; set; }
        public Nullable<int> OLD_TNVN_AUTO_PSGR_PCLAIM_ID { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_PSGR_PCLAIM { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_PRICE { get; set; }
        public Nullable<float> OLD_TNVN_AUTO_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_VAT { get; set; }
        public Nullable<int> OLD_TNDSTN_ADD_AUTO_TYPE { get; set; }
        public Nullable<int> OLD_TNDSTN_ADD_AUTO_PCLAIM_ID { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_AUTO_ASSEST { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_AUTO_CREW { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_AUTO_PRICE { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_AUTO_VAT { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_AUTO_PSGR { get; set; }
        public Nullable<int> OLD_TNDS_AUTO_LOAD_TYPE { get; set; }
        public Nullable<decimal> OLD_TNDS_AUTO_LOAD_LMT { get; set; }
        public Nullable<decimal> OLD_TNDS_AUTO_LOAD_DEDUCT { get; set; }
        public string OLD_TNDS_AUTO_LOAD_OWN { get; set; }
        public Nullable<decimal> OLD_TNDS_AUTO_LOAD_PRICE { get; set; }
        public Nullable<decimal> OLD_TNDS_AUTO_LOAD_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_TNDS_AUTO_LOAD_VAT { get; set; }
        public Nullable<decimal> OLD_VC_AUTO_VEH_VALUE { get; set; }
        public Nullable<decimal> OLD_VS_AUTO_INSURE_VAL { get; set; }
        public Nullable<decimal> OLD_VC_AUTO_CLAIM_DEDUCT { get; set; }
        public Nullable<decimal> OLD_VC_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_VC_AUTO_DE_PRICE_RATIO { get; set; }
        public Nullable<decimal> OLD_VC_AUTO_PRICE { get; set; }
        public Nullable<decimal> OLD_VC_AUTO_VAT { get; set; }
        public Nullable<int> OLD_TNVN_MOTO_PCLAIM_ID { get; set; }
        public Nullable<decimal> OLD_TNVN_MOTO_PCLAIM { get; set; }
        public Nullable<decimal> OLD_TNVN_MOTO_PRICE { get; set; }
        public Nullable<decimal> OLD_TNVN_MOTO_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_TNVN_MOTO_VAT { get; set; }
        public Nullable<decimal> OLD_VC_MOTO_VEH_VALUE { get; set; }
        public Nullable<decimal> OLD_VC_MOTO_INSURE_VAL { get; set; }
        public Nullable<decimal> OLD_VC_MOTO_CLAIM_DEDUCT { get; set; }
        public Nullable<decimal> OLD_VC_MOTO_PRICE { get; set; }
        public Nullable<decimal> OLD_VC_MOTO_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_VC_MOTO_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_VC_MOTO_VAT { get; set; }
        public string OLD_STATUS_RECORD { get; set; }
        public Nullable<int> OLD_TNDSTN_ADD_MOTO_TYPE { get; set; }
        public Nullable<int> OLD_TNDSTN_ADD_MOTO_PCLAIM_ID { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_MOTO_ASSEST { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_MOTO_CREW { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_MOTO_PSGR { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_PRICE { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_VAT { get; set; }
        public Nullable<System.DateTime> OLD_CREATE_DATE { get; set; }
        public Nullable<int> OLD_CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> OLD_UPDATE_DATE { get; set; }
        public Nullable<int> OLD_UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> OLD_SUBMIT_DATE { get; set; }
        public Nullable<int> OLD_APPROVE_USER_ID { get; set; }
        public Nullable<System.DateTime> OLD_APPROVE_DATE { get; set; }
        public string OLD_CONTRACT_CODE { get; set; }
        public string OLD_AGENT_NAME { get; set; }
        public Nullable<int> OLD_AGENT_ID { get; set; }
        public string OLD_AGENT_CODE { get; set; }
        public Nullable<int> OLD_APPROVAL_AGENT_ID { get; set; }
        public string OLD_APPROVAL_AGENT_CODE { get; set; }
        public string OLD_APPROVAL_AGENT_NAME { get; set; }
        public Nullable<int> OLD_DIVN_ID { get; set; }
        public string OLD_DIVN_CODE { get; set; }
        public string OLD_DIVN_NAME { get; set; }
        public Nullable<int> OLD_INSUR_PRODUCT_ID { get; set; }
        public string OLD_INSUR_PRODUCT_CODE { get; set; }
        public string OLD_INSUR_PRODUCT_NAME { get; set; }
        public string OLD_TAX_NO { get; set; }
        public Nullable<int> OLD_AGENT_ID_C_1 { get; set; }
        public Nullable<int> OLD_AGENT_ID_C_2 { get; set; }
        public Nullable<int> OLD_AGENT_ID_C_3 { get; set; }
        public Nullable<int> OLD_AGENT_ID_C_4 { get; set; }
        public Nullable<int> OLD_AGENT_ID_C_5 { get; set; }
        public Nullable<int> OLD_AGENT_ID_C_6 { get; set; }
        public Nullable<int> OLD_AGENT_ID_C_7 { get; set; }
        public Nullable<int> OLD_AGENT_ID_C_8 { get; set; }
        public Nullable<int> OLD_AGENT_ID_C_9 { get; set; }
        public Nullable<int> OLD_AGENT_ID_C_10 { get; set; }
        public Nullable<int> NEW_CUSTOMER_ID { get; set; }
        public Nullable<int> NEW_CUST_ACCOUNT_ID { get; set; }
        public string NEW_CUST_TYPE { get; set; }
        public string NEW_CUST_NAME { get; set; }
        public string NEW_IDENTITY_NO { get; set; }
        public string NEW_CUST_PHONE { get; set; }
        public string NEW_CUST_EMAIL { get; set; }
        public string NEW_CUST_ADDRESS { get; set; }
        public Nullable<int> NEW_CUST_COUNTRY_ID { get; set; }
        public Nullable<int> NEW_CUST_PROVINCE_ID { get; set; }
        public Nullable<int> NEW_CUST_DISTRICT_ID { get; set; }
        public Nullable<int> NEW_CUS_WARD_ID { get; set; }
        public string NEW_BEN_NAME { get; set; }
        public string NEW_BEN_IDENTITY_ID { get; set; }
        public string NEW_BEN_PHONE { get; set; }
        public Nullable<int> NEW_INPUTING_USER_ID { get; set; }
        public Nullable<int> NEW_CONTRACT_STATUS { get; set; }
        public string NEW_BILL_NAME { get; set; }
        public string NEW_BILL_IDENTITY_NO { get; set; }
        public string NEW_BILL_IDENTITY_TYPE { get; set; }
        public Nullable<int> NEW_BILL_COUNTRY_ID { get; set; }
        public Nullable<int> NEW_BILL_PROVINCE_ID { get; set; }
        public Nullable<int> NEW_BILL_DISTRICT_ID { get; set; }
        public Nullable<int> NEW_BILL_WARD_ID { get; set; }
        public string NEW_BILL_ADDRESS { get; set; }
        public string NEW_VEH_PLATE_NO { get; set; }
        public string NEW_VEH_FRAME_NO { get; set; }
        public string NEW_VEH_ENGINE_NO { get; set; }
        public Nullable<int> NEW_VEH_BRAND_ID { get; set; }
        public Nullable<int> NEW_VEH_MODEL_ID { get; set; }
        public Nullable<int> NEW_VEH_TYPE_ID { get; set; }
        public Nullable<decimal> NEW_VEH_CUBE_CAPACITY { get; set; }
        public Nullable<decimal> NEW_VEH_MAX_LOAD { get; set; }
        public Nullable<short> NEW_VEH_SEAT_NO { get; set; }
        public Nullable<int> NEW_VEH_ORIGIN { get; set; }
        public Nullable<System.DateTime> NEW_VEH_FIRST_REG_DATE { get; set; }
        public Nullable<int> NEW_VEH_PURPOSE_ID { get; set; }
        public Nullable<decimal> NEW_VEH_VALUE { get; set; }
        public Nullable<int> NEW_SALE_AGENT_ID { get; set; }
        public string NEW_SALE_AGENT_CODE { get; set; }
        public Nullable<int> NEW_SALE_ACCOUNT_ID { get; set; }
        public string NEW_SALE_PERSONEL_CODE { get; set; }
        public string NEW_CONTRACT_CERT_NO { get; set; }
        public string NEW_CONTRACT_PRINT_NO { get; set; }
        public Nullable<System.DateTime> NEW_CONTRACT_ISSUED_DATE { get; set; }
        public Nullable<System.DateTime> NEW_CONTRACT_START_DATE { get; set; }
        public Nullable<System.DateTime> NEW_CONTRACT_EXPIRE_DATE { get; set; }
        public string NEW_CONTRACT_ISSUE_TYPE { get; set; }
        public Nullable<decimal> NEW_INSURED_TOTAL_VAL { get; set; }
        public Nullable<decimal> NEW_DEDUCT_TOTAL_VAL { get; set; }
        public Nullable<decimal> NEW_TOTAL_PRICE { get; set; }
        public Nullable<decimal> NEW_TOTAL_DEDUCT_PRICE { get; set; }
        public Nullable<decimal> NEW_TOTAL_DEDUCT_RATIO { get; set; }
        public string NEW_IDENTITY_TYPE { get; set; }
        public Nullable<decimal> NEW_DISCOUNT { get; set; }
        public Nullable<int> NEW_DISCOUNT_PROG_ID { get; set; }
        public string NEW_DISCOUNT_PROG_NAME { get; set; }
        public Nullable<decimal> NEW_DISCOUNT_RATIO { get; set; }
        public Nullable<float> NEW_TOTAL_VAT { get; set; }
        public Nullable<int> NEW_PAY_METHOD { get; set; }
        public Nullable<System.DateTime> NEW_PAY_DUE_DATE { get; set; }
        public Nullable<decimal> NEW_TNDSBB_AUTO_PRICE { get; set; }
        public Nullable<decimal> NEW_TNDSBB_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_TNSDBB_AUTO_VAT { get; set; }
        public Nullable<decimal> NEW_TNDSBB_MOTO_PRICE { get; set; }
        public Nullable<decimal> NEW_TNDSBB_MOTO_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_TNDSBB_MOTO_VAT { get; set; }
        public Nullable<short> NEW_TNVN_AUTO_CREW_NO { get; set; }
        public Nullable<int> NEW_TNVN_AUTO_CREW_PCLAIM_ID { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_CREW_PCLAIM { get; set; }
        public Nullable<short> NEW_TNVN_AUTO_PSGR_NO { get; set; }
        public Nullable<int> NEW_TNVN_AUTO_PSGR_PCLAIM_ID { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_PSGR_PCLAIM { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_PRICE { get; set; }
        public Nullable<float> NEW_TNVN_AUTO_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_VAT { get; set; }
        public Nullable<int> NEW_TNDSTN_ADD_AUTO_TYPE { get; set; }
        public Nullable<int> NEW_TNDSTN_ADD_AUTO_PCLAIM_ID { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_AUTO_ASSEST { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_AUTO_CREW { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_AUTO_PRICE { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_AUTO_VAT { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_AUTO_PSGR { get; set; }
        public Nullable<int> NEW_TNDS_AUTO_LOAD_TYPE { get; set; }
        public Nullable<decimal> NEW_TNDS_AUTO_LOAD_LMT { get; set; }
        public Nullable<decimal> NEW_TNDS_AUTO_LOAD_DEDUCT { get; set; }
        public string NEW_TNDS_AUTO_LOAD_OWN { get; set; }
        public Nullable<decimal> NEW_TNDS_AUTO_LOAD_PRICE { get; set; }
        public Nullable<decimal> NEW_TNDS_AUTO_LOAD_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_TNDS_AUTO_LOAD_VAT { get; set; }
        public Nullable<decimal> NEW_VC_AUTO_VEH_VALUE { get; set; }
        public Nullable<decimal> NEW_VS_AUTO_INSURE_VAL { get; set; }
        public Nullable<decimal> NEW_VC_AUTO_CLAIM_DEDUCT { get; set; }
        public Nullable<decimal> NEW_VC_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_VC_AUTO_DE_PRICE_RATIO { get; set; }
        public Nullable<decimal> NEW_VC_AUTO_PRICE { get; set; }
        public Nullable<decimal> NEW_VC_AUTO_VAT { get; set; }
        public Nullable<int> NEW_TNVN_MOTO_PCLAIM_ID { get; set; }
        public Nullable<decimal> NEW_TNVN_MOTO_PCLAIM { get; set; }
        public Nullable<decimal> NEW_TNVN_MOTO_PRICE { get; set; }
        public Nullable<decimal> NEW_TNVN_MOTO_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_TNVN_MOTO_VAT { get; set; }
        public Nullable<decimal> NEW_VC_MOTO_VEH_VALUE { get; set; }
        public Nullable<decimal> NEW_VC_MOTO_INSURE_VAL { get; set; }
        public Nullable<decimal> NEW_VC_MOTO_CLAIM_DEDUCT { get; set; }
        public Nullable<decimal> NEW_VC_MOTO_PRICE { get; set; }
        public Nullable<decimal> NEW_VC_MOTO_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_VC_MOTO_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_VC_MOTO_VAT { get; set; }
        public string NEW_STATUS_RECORD { get; set; }
        public Nullable<int> NEW_TNDSTN_ADD_MOTO_TYPE { get; set; }
        public Nullable<int> NEW_TNDSTN_ADD_MOTO_PCLAIM_ID { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_MOTO_ASSEST { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_MOTO_CREW { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_MOTO_PSGR { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_PRICE { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_VAT { get; set; }
        public Nullable<System.DateTime> NEW_CREATE_DATE { get; set; }
        public Nullable<int> NEW_CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> NEW_UPDATE_DATE { get; set; }
        public Nullable<int> NEW_UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> NEW_SUBMIT_DATE { get; set; }
        public Nullable<int> NEW_APPROVE_USER_ID { get; set; }
        public Nullable<System.DateTime> NEW_APPROVE_DATE { get; set; }
        public string NEW_CONTRACT_CODE { get; set; }
        public string NEW_AGENT_NAME { get; set; }
        public Nullable<int> NEW_AGENT_ID { get; set; }
        public string NEW_AGENT_CODE { get; set; }
        public Nullable<int> NEW_APPROVAL_AGENT_ID { get; set; }
        public string NEW_APPROVAL_AGENT_CODE { get; set; }
        public string NEW_APPROVAL_AGENT_NAME { get; set; }
        public Nullable<int> NEW_DIVN_ID { get; set; }
        public string NEW_DIVN_CODE { get; set; }
        public string NEW_DIVN_NAME { get; set; }
        public Nullable<int> NEW_INSUR_PRODUCT_ID { get; set; }
        public string NEW_INSUR_PRODUCT_CODE { get; set; }
        public string NEW_INSUR_PRODUCT_NAME { get; set; }
        public string NEW_TAX_NO { get; set; }
        public Nullable<int> NEW_AGENT_ID_C_1 { get; set; }
        public Nullable<int> NEW_AGENT_ID_C_2 { get; set; }
        public Nullable<int> NEW_AGENT_ID_C_3 { get; set; }
        public Nullable<int> NEW_AGENT_ID_C_4 { get; set; }
        public Nullable<int> NEW_AGENT_ID_C_5 { get; set; }
        public Nullable<int> NEW_AGENT_ID_C_6 { get; set; }
        public Nullable<int> NEW_AGENT_ID_C_7 { get; set; }
        public Nullable<int> NEW_AGENT_ID_C_8 { get; set; }
        public Nullable<int> NEW_AGENT_ID_C_9 { get; set; }
        public Nullable<int> NEW_AGENT_ID_C_10 { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_CREW_PRICE { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_CREW_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_CREW_VAT { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_PSGR_PRICE { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_PSGR_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_PSGR_VAT { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_CREW_PRICE { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_CREW_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_CREW_VAT { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_PSGR_PRICE { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_PSGR_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_PSGR_VAT { get; set; }
        public Nullable<short> OLD_ALTER_TIMES { get; set; }
        public Nullable<short> NEW_ALTER_TIMES { get; set; }
        public Nullable<System.DateTime> OLD_IDENTITY_ISSUE_DATE { get; set; }
        public string OLD_IDENTITY_ISSUE_OFFICE { get; set; }
        public string OLD_NATIONALITY { get; set; }
        public Nullable<System.DateTime> OLD_DOB { get; set; }
        public Nullable<System.DateTime> NEW_IDENTITY_ISSUE_DATE { get; set; }
        public string NEW_IDENTITY_ISSUE_OFFICE { get; set; }
        public string NEW_NATIONALITY { get; set; }
        public Nullable<System.DateTime> NEW_DOB { get; set; }
        public string OLD_BILL_COMPANY { get; set; }
        public string NEW_BILL_TAXNO { get; set; }
        public string OLD_BILL_TAXNO { get; set; }
        public string NEW_BILL_COMPANY { get; set; }
        public Nullable<decimal> NEW_TNDSBB_AUTO_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_TNDSBB_MOTO_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_AUTO_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_MOTO_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_TNDS_AUTO_LOAD_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_TNVN_MOTO_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_CREW_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_TNVN_AUTO_PSGR_DE_RATIO { get; set; }
        public Nullable<int> NEW_HEALTH_CANCER_PACKAGE_ID { get; set; }
        public Nullable<decimal> NEW_HEALTH_CANCER_INSURED_LVL { get; set; }
        public Nullable<decimal> NEW_HEALTH_CANCER_INSURED_VAL { get; set; }
        public Nullable<decimal> NEW_HEALTH_CANCER_DEDUCT { get; set; }
        public Nullable<decimal> NEW_HEALTH_CANCER_PRICE { get; set; }
        public Nullable<decimal> NEW_HEALTH_CANCER_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_HEALTH_CANCER_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_HEALTH_CANCER_VAT { get; set; }
        public Nullable<decimal> NEW_HEALTH_DISEASE_PACKAGE_ID { get; set; }
        public Nullable<decimal> NEW_HEALTH_DISEASE_INSURED_LVL { get; set; }
        public Nullable<decimal> NEW_HEALTH_DISEASE_INSURED_VAL { get; set; }
        public Nullable<decimal> NEW_HEALTH_DISEASE_DEDUCT { get; set; }
        public Nullable<decimal> NEW_HEALTH_DISEASE_PRICE { get; set; }
        public Nullable<decimal> NEW_HEALTH_DISEASE_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_HEALTH_DISEASE_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_HEALTH_DISEASE_VAT { get; set; }
        public Nullable<decimal> OLD_TNDSBB_AUTO_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_TNDSBB_MOTO_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_AUTO_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_MOTO_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_TNDS_AUTO_LOAD_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_TNVN_MOTO_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_CREW_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_TNVN_AUTO_PSGR_DE_RATIO { get; set; }
        public Nullable<int> OLD_HEALTH_CANCER_PACKAGE_ID { get; set; }
        public Nullable<decimal> OLD_HEALTH_CANCER_INSURED_LVL { get; set; }
        public Nullable<decimal> OLD_HEALTH_CANCER_INSURED_VAL { get; set; }
        public Nullable<decimal> OLD_HEALTH_CANCER_DEDUCT { get; set; }
        public Nullable<decimal> OLD_HEALTH_CANCER_PRICE { get; set; }
        public Nullable<decimal> OLD_HEALTH_CANCER_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_HEALTH_CANCER_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_HEALTH_CANCER_VAT { get; set; }
        public Nullable<decimal> OLD_HEALTH_DISEASE_PACKAGE_ID { get; set; }
        public Nullable<decimal> OLD_HEALTH_DISEASE_INSURED_LVL { get; set; }
        public Nullable<decimal> OLD_HEALTH_DISEASE_INSURED_VAL { get; set; }
        public Nullable<decimal> OLD_HEALTH_DISEASE_DEDUCT { get; set; }
        public Nullable<decimal> OLD_HEALTH_DISEASE_PRICE { get; set; }
        public Nullable<decimal> OLD_HEALTH_DISEASE_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_HEALTH_DISEASE_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_HEALTH_DISEASE_VAT { get; set; }
        public string OLD_REPRESENTATIVE_NAME { get; set; }
        public string NEW_REPRESENTATIVE_NAME { get; set; }
        public Nullable<decimal> OLD_TRAVEL_PRICE_ORIGIN { get; set; }
        public Nullable<decimal> NEW_TRAVEL_PRICE_ORIGIN { get; set; }
        public Nullable<decimal> OLD_TRAVEL_EXCHANGE_RATE { get; set; }
        public Nullable<decimal> NEW_TRAVEL_EXCHANGE_RATE { get; set; }
        public string OLD_INSUR_PRODUCT_TYPE { get; set; }
        public string NEW_INSUR_PRODUCT_TYPE { get; set; }
        public string OLD_CUST_CODE { get; set; }
        public string NEW_CUST_CODE { get; set; }
        public Nullable<int> OLD_BEN_RELATIONSHIP_ID { get; set; }
        public string OLD_BEN_RELATIONSHIP_CODE { get; set; }
        public string OLD_BEN_RELATIONSHIP_NAME { get; set; }
        public Nullable<int> NEW_BEN_RELATIONSHIP_ID { get; set; }
        public string NEW_BEN_RELATIONSHIP_CODE { get; set; }
        public string NEW_BEN_RELATIONSHIP_NAME { get; set; }
        public string OLD_TRAVEL_MODEL { get; set; }
        public string NEW_TRAVEL_MODEL { get; set; }
        public string OLD_TRAVEL_GAME { get; set; }
        public string NEW_TRAVEL_GAME { get; set; }
        public string OLD_TRAVEL_DANGER_GAME { get; set; }
        public string NEW_TRAVEL_DANGER_GAME { get; set; }
        public string OLD_VEH_REGISTRATION_IMAGE { get; set; }
        public string OLD_VEH_FRONT_IMAGE { get; set; }
        public string OLD_VEH_BACK_IMAGE { get; set; }
        public string OLD_VEH_LEFT_IMAGE { get; set; }
        public string OLD_VEH_RIGHT_IMAGE { get; set; }
        public string NEW_VEH_REGISTRATION_IMAGE { get; set; }
        public string NEW_VEH_FRONT_IMAGE { get; set; }
        public string NEW_VEH_BACK_IMAGE { get; set; }
        public string NEW_VEH_LEFT_IMAGE { get; set; }
        public string NEW_VEH_RIGHT_IMAGE { get; set; }
        public Nullable<int> OLD_DEPT_ID { get; set; }
        public string OLD_DEPT_CODE { get; set; }
        public string OLD_DEPT_NAME { get; set; }
        public Nullable<int> OLD_NUMBER_START { get; set; }
        public Nullable<int> OLD_NUMBER_END { get; set; }
        public Nullable<int> OLD_NUMBER_CURENT { get; set; }
        public Nullable<int> NEW_DEPT_ID { get; set; }
        public string NEW_DEPT_CODE { get; set; }
        public string NEW_DEPT_NAME { get; set; }
        public Nullable<int> NEW_NUMBER_START { get; set; }
        public Nullable<int> NEW_NUMBER_END { get; set; }
        public Nullable<int> NEW_NUMBER_CURENT { get; set; }
        public string OLD_HINS_OWNERSHIP { get; set; }
        public string NEW_HINS_OWNERSHIP { get; set; }
        public string OLD_HINS_USINGTIME { get; set; }
        public string NEW_HINS_USINGTIME { get; set; }
        public string OLD_HINS_ADDRESS { get; set; }
        public string NEW_HINS_ADDRESS { get; set; }
        public string OLD_HINS_AUTOFIREFIGHTINGSYS { get; set; }
        public string NEW_HINS_AUTOFIREFIGHTINGSYS { get; set; }
        public string OLD_HINS_BANKMORTGAGE { get; set; }
        public string NEW_HINS_BANKMORTGAGE { get; set; }
        public string OLD_HINS_NAME_OF_BANK { get; set; }
        public string NEW_HINS_NAME_OF_BANK { get; set; }
        public string OLD_HINS_PHONE_OF_BANK { get; set; }
        public string NEW_HINS_PHONE_OF_BANK { get; set; }
        public string OLD_HINS_EMAIL_OF_BANK { get; set; }
        public string NEW_HINS_EMAIL_OF_BANK { get; set; }
        public string OLD_HINS_ADDRESS_OF_BANK { get; set; }
        public string NEW_HINS_ADDRESS_OF_BANK { get; set; }
        public string OLD_BILL_COMPANY_ADDRESS { get; set; }
        public Nullable<int> OLD_CURRENCY_ID { get; set; }
        public string OLD_CURRENCY_CODE { get; set; }
        public string OLD_CURRENCY_NAME { get; set; }
        public string NEW_BILL_COMPANY_ADDRESS { get; set; }
        public Nullable<int> NEW_CURRENCY_ID { get; set; }
        public string NEW_CURRENCY_CODE { get; set; }
        public string NEW_CURRENCY_NAME { get; set; }
        public Nullable<decimal> OLD_HINS_HOME_VALUE { get; set; }
        public Nullable<decimal> NEW_HINS_HOME_VALUE { get; set; }
        public Nullable<decimal> OLD_HINS_HOME_INSUR_VALUE { get; set; }
        public Nullable<decimal> NEW_HINS_HOME_INSUR_VALUE { get; set; }
        public string OLD_HINS_JOIN_VOLUNTARY_FIRE { get; set; }
        public string NEW_HINS_JOIN_VOLUNTARY_FIRE { get; set; }
        public Nullable<decimal> OLD_HINS_ASSETS_VALUE { get; set; }
        public Nullable<decimal> NEW_HINS_ASSETS_VALUE { get; set; }
        public Nullable<decimal> OLD_HINS_DEDUCTION_VALUE { get; set; }
        public Nullable<decimal> NEW_HINS_DEDUCTION_VALUE { get; set; }
        public string OLD_VEH_TYPE_NAME { get; set; }
        public Nullable<int> OLD_INSUR_PRODUCT_TYPE_ID { get; set; }
        public string OLD_INSUR_PRODUCT_TYPE_NAME { get; set; }
        public string NEW_VEH_TYPE_NAME { get; set; }
        public Nullable<int> NEW_INSUR_PRODUCT_TYPE_ID { get; set; }
        public string NEW_INSUR_PRODUCT_TYPE_NAME { get; set; }
        public Nullable<decimal> OLD_HINS_VALUE_FEE_RATIO { get; set; }
        public Nullable<decimal> NEW_HINS_VALUE_FEE_RATIO { get; set; }
        public Nullable<decimal> OLD_TRAVEL_COMMISSION { get; set; }
        public Nullable<decimal> NEW_TRAVEL_COMMISSION { get; set; }
        public string OLD_TRAVEL_COST_BASIC_CODE { get; set; }
        public string NEW_TRAVEL_COST_BASIC_CODE { get; set; }
        public string OLD_BEN_EMAIL { get; set; }
        public string NEW_BEN_EMAIL { get; set; }
        public string OLD_BEN_ADDRESS { get; set; }
        public string NEW_BEN_ADDRESS { get; set; }
        public Nullable<int> OLD_TRAVEL_AREA_FROM_ID { get; set; }
        public string OLD_TRAVEL_AREA_FROM_NAME { get; set; }
        public Nullable<int> OLD_TRAVEL_AREA_TO_ID { get; set; }
        public string OLD_TRAVEL_AREA_TO_NAME { get; set; }
        public Nullable<System.DateTime> OLD_TRAVEL_DEPART_DATE { get; set; }
        public Nullable<System.DateTime> OLD_TRAVEL_RETURN_DATE { get; set; }
        public Nullable<decimal> OLD_TRAVEL_PRICE { get; set; }
        public Nullable<decimal> OLD_TRAVEL_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_TRAVEL_RATIO { get; set; }
        public Nullable<decimal> OLD_TRAVEL_TOTAL_PRICE { get; set; }
        public Nullable<int> NEW_TRAVEL_AREA_FROM_ID { get; set; }
        public string NEW_TRAVEL_AREA_FROM_NAME { get; set; }
        public Nullable<int> NEW_TRAVEL_AREA_TO_ID { get; set; }
        public string NEW_TRAVEL_AREA_TO_NAME { get; set; }
        public Nullable<System.DateTime> NEW_TRAVEL_DEPART_DATE { get; set; }
        public Nullable<System.DateTime> NEW_TRAVEL_RETURN_DATE { get; set; }
        public Nullable<decimal> NEW_TRAVEL_PRICE { get; set; }
        public Nullable<decimal> NEW_TRAVEL_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_TRAVEL_RATIO { get; set; }
        public Nullable<decimal> NEW_TRAVEL_TOTAL_PRICE { get; set; }
        public Nullable<decimal> OLD_HINS_INSUR_WITHOUT_VAT { get; set; }
        public Nullable<decimal> NEW_HINS_INSUR_WITHOUT_VAT { get; set; }
        public Nullable<decimal> OLD_HINS_HOME_VALUE_FEERATE { get; set; }
        public Nullable<decimal> NEW_HINS_HOME_VALUE_FEERATE { get; set; }
        public Nullable<decimal> OLD_HINS_ASSETS_WITHOUT_VAT { get; set; }
        public Nullable<decimal> NEW_HINS_ASSETS_WITHOUT_VAT { get; set; }
        public Nullable<decimal> OLD_HINS_ASSETS_VALUE_FEERATE { get; set; }
        public Nullable<decimal> NEW_HINS_ASSETS_VALUE_FEERATE { get; set; }
        public Nullable<decimal> OLD_HINS_INSUR_AFTER_DAMAGE { get; set; }
        public Nullable<decimal> NEW_HINS_INSUR_AFTER_DAMAGE { get; set; }
        public Nullable<decimal> OLD_HINS_AFTER_DAMAGE_NO_VAT { get; set; }
        public Nullable<decimal> NEW_HINS_AFTER_DAMAGE_NO_VAT { get; set; }
        public Nullable<decimal> OLD_HINS_AFTER_DAMAGE_FEERATE { get; set; }
        public Nullable<decimal> NEW_HINS_AFTER_DAMAGE_FEERATE { get; set; }
        public string OLD_HINS_LOAN_CONTRACT_NO { get; set; }
        public string NEW_HINS_LOAN_CONTRACT_NO { get; set; }
        public Nullable<decimal> OLD_HEALTH_COMMISSION { get; set; }
        public Nullable<decimal> NEW_HEALTH_COMMISSION { get; set; }
        public string OLD_HEALTH_COST_BASIC_CODE { get; set; }
        public string NEW_HEALTH_COST_BASIC_CODE { get; set; }
        public Nullable<decimal> OLD_AUTO_BB_COMMISSION { get; set; }
        public Nullable<decimal> NEW_AUTO_BB_COMMISSION { get; set; }
        public string OLD_AUTO_BB_COST_BASIC_CODE { get; set; }
        public string NEW_AUTO_BB_COST_BASIC_CODE { get; set; }
        public Nullable<decimal> OLD_AUTO_ADD_COMMISSION { get; set; }
        public Nullable<decimal> NEW_AUTO_ADD_COMMISSION { get; set; }
        public string OLD_AUTO_ADD_COST_BASIC_CODE { get; set; }
        public string NEW_AUTO_ADD_COST_BASIC_CODE { get; set; }
        public Nullable<decimal> OLD_AUTO_CREW_COMMISSION { get; set; }
        public Nullable<decimal> NEW_AUTO_CREW_COMMISSION { get; set; }
        public string OLD_AUTO_CREW_COST_BASIC_CODE { get; set; }
        public string NEW_AUTO_CREW_COST_BASIC_CODE { get; set; }
        public Nullable<decimal> OLD_AUTO_PSGR_COMMISSION { get; set; }
        public Nullable<decimal> NEW_AUTO_PSGR_COMMISSION { get; set; }
        public string OLD_AUTO_PSGR_COST_BASIC_CODE { get; set; }
        public string NEW_AUTO_PSGR_COST_BASIC_CODE { get; set; }
        public Nullable<decimal> OLD_AUTO_LOAD_COMMISSION { get; set; }
        public Nullable<decimal> NEW_AUTO_LOAD_COMMISSION { get; set; }
        public string OLD_AUTO_LOAD_COST_BASIC_CODE { get; set; }
        public string NEW_AUTO_LOAD_COST_BASIC_CODE { get; set; }
        public Nullable<decimal> OLD_MOTO_BB_COMMISSION { get; set; }
        public Nullable<decimal> NEW_MOTO_BB_COMMISSION { get; set; }
        public string OLD_MOTO_BB_COST_BASIC_CODE { get; set; }
        public string NEW_MOTO_BB_COST_BASIC_CODE { get; set; }
        public Nullable<decimal> OLD_MOTO_ADD_COMMISSION { get; set; }
        public Nullable<decimal> NEW_MOTO_ADD_COMMISSION { get; set; }
        public string OLD_MOTO_ADD_COST_BASIC_CODE { get; set; }
        public string NEW_MOTO_ADD_COST_BASIC_CODE { get; set; }
        public Nullable<decimal> OLD_MOTO_VN_COMMISSION { get; set; }
        public Nullable<decimal> NEW_MOTO_VN_COMMISSION { get; set; }
        public string OLD_MOTO_VN_COST_BASIC_CODE { get; set; }
        public string NEW_MOTO_VN_COST_BASIC_CODE { get; set; }
        public Nullable<decimal> OLD_AUTO_BB_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> NEW_AUTO_BB_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> OLD_AUTO_VN_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> NEW_AUTO_VN_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> OLD_AUTO_ADD_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> NEW_AUTO_ADD_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> OLD_AUTO_LOAD_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> NEW_AUTO_LOAD_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> OLD_MOTO_BB_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> NEW_MOTO_BB_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> OLD_MOTO_VN_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> NEW_MOTO_VN_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> OLD_MOTO_ADD_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> NEW_MOTO_ADD_VAT_BEFORE_ALTER { get; set; }
        public Nullable<decimal> OLD_TNDSTN_ADD_AUTO_PCLAIM { get; set; }
        public Nullable<decimal> NEW_TNDSTN_ADD_AUTO_PCLAIM { get; set; }
        public Nullable<decimal> OLD_TOTAL_ALTERED_PRICE { get; set; }
        public Nullable<decimal> NEW_TOTAL_ALTERED_PRICE { get; set; }
        public Nullable<decimal> OLD_TOTAL_FINAL_PRICE { get; set; }
        public Nullable<decimal> NEW_TOTAL_FINAL_PRICE { get; set; }
        public Nullable<decimal> OLD_AUTO_VC_COMMISSION { get; set; }
        public Nullable<decimal> NEW_AUTO_VC_COMMISSION { get; set; }
        public string OLD_AUTO_VC_COST_BASIC_CODE { get; set; }
        public string NEW_AUTO_VC_COST_BASIC_CODE { get; set; }
        public Nullable<decimal> OLD_HINS_COMMISSION { get; set; }
        public Nullable<decimal> NEW_HINS_COMMISSION { get; set; }
        public string OLD_HINS_COST_BASIC_CODE { get; set; }
        public string NEW_HINS_COST_BASIC_CODE { get; set; }
        public Nullable<int> NEW_AGENT_ACCOUNT_ID_C_1 { get; set; }
        public Nullable<int> NEW_AGENT_ACCOUNT_ID_C_2 { get; set; }
        public Nullable<int> NEW_AGENT_ACCOUNT_ID_C_3 { get; set; }
        public Nullable<int> NEW_AGENT_ACCOUNT_ID_C_4 { get; set; }
        public Nullable<int> NEW_AGENT_ACCOUNT_ID_C_5 { get; set; }
        public Nullable<int> NEW_AGENT_ACCOUNT_ID_C_6 { get; set; }
        public Nullable<int> NEW_AGENT_ACCOUNT_ID_C_7 { get; set; }
        public Nullable<int> NEW_AGENT_ACCOUNT_ID_C_8 { get; set; }
        public Nullable<int> NEW_AGENT_ACCOUNT_ID_C_9 { get; set; }
        public Nullable<int> NEW_AGENT_ACCOUNT_ID_C_10 { get; set; }
        public Nullable<int> OLD_AGENT_ACCOUNT_ID_C_1 { get; set; }
        public Nullable<int> OLD_AGENT_ACCOUNT_ID_C_2 { get; set; }
        public Nullable<int> OLD_AGENT_ACCOUNT_ID_C_3 { get; set; }
        public Nullable<int> OLD_AGENT_ACCOUNT_ID_C_4 { get; set; }
        public Nullable<int> OLD_AGENT_ACCOUNT_ID_C_5 { get; set; }
        public Nullable<int> OLD_AGENT_ACCOUNT_ID_C_6 { get; set; }
        public Nullable<int> OLD_AGENT_ACCOUNT_ID_C_7 { get; set; }
        public Nullable<int> OLD_AGENT_ACCOUNT_ID_C_8 { get; set; }
        public Nullable<int> OLD_AGENT_ACCOUNT_ID_C_9 { get; set; }
        public Nullable<int> OLD_AGENT_ACCOUNT_ID_C_10 { get; set; }
        public Nullable<int> OLD_VEH_TNDSTT_TYPE_ID { get; set; }
        public Nullable<int> NEW_VEH_TNDSTT_TYPE_ID { get; set; }
        public Nullable<int> OLD_HINS_PROVINCE { get; set; }
        public Nullable<int> NEW_HINS_PROVINCE { get; set; }
        public Nullable<int> OLD_HINS_DISTRICT { get; set; }
        public Nullable<int> NEW_HINS_DISTRICT { get; set; }
        public Nullable<int> OLD_HINS_WARD { get; set; }
        public Nullable<int> NEW_HINS_WARD { get; set; }
        public string OLD_HINS_HOUSETYPE { get; set; }
        public string NEW_HINS_HOUSETYPE { get; set; }
        public string OLD_HINS_KINDOFHOUSE { get; set; }
        public string NEW_HINS_KINDOFHOUSE { get; set; }
        public Nullable<decimal> OLD_HINS_HOME_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_HINS_HOME_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_HINS_HOME_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_HINS_HOME_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_HINS_HOME_PRICE { get; set; }
        public Nullable<decimal> NEW_HINS_HOME_PRICE { get; set; }
        public Nullable<decimal> OLD_HINS_HOME_TOTAL_PRICE { get; set; }
        public Nullable<decimal> NEW_HINS_HOME_TOTAL_PRICE { get; set; }
        public Nullable<decimal> OLD_HINS_HOME_VAT { get; set; }
        public Nullable<decimal> NEW_HINS_HOME_VAT { get; set; }
        public Nullable<decimal> OLD_HINS_ASSETS_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_HINS_ASSETS_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_HINS_ASSETS_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_HINS_ASSETS_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_HINS_ASSETS_PRICE { get; set; }
        public Nullable<decimal> NEW_HINS_ASSETS_PRICE { get; set; }
        public Nullable<decimal> OLD_HINS_ASSETS_TOTAL_PRICE { get; set; }
        public Nullable<decimal> NEW_HINS_ASSETS_TOTAL_PRICE { get; set; }
        public Nullable<decimal> OLD_HINS_ASSETS_VAT { get; set; }
        public Nullable<decimal> NEW_HINS_ASSETS_VAT { get; set; }
        public Nullable<decimal> OLD_HINS_DAMAGE_DE_RATIO { get; set; }
        public Nullable<decimal> NEW_HINS_DAMAGE_DE_RATIO { get; set; }
        public Nullable<decimal> OLD_HINS_DAMAGE_DE_PRICE { get; set; }
        public Nullable<decimal> NEW_HINS_DAMAGE_DE_PRICE { get; set; }
        public Nullable<decimal> OLD_HINS_DAMAGE_PRICE { get; set; }
        public Nullable<decimal> NEW_HINS_DAMAGE_PRICE { get; set; }
        public Nullable<decimal> OLD_HINS_DAMAGE_TOTAL_PRICE { get; set; }
        public Nullable<decimal> NEW_HINS_DAMAGE_TOTAL_PRICE { get; set; }
        public Nullable<decimal> OLD_HINS_DAMAGE_VAT { get; set; }
        public Nullable<decimal> NEW_HINS_DAMAGE_VAT { get; set; }
        public Nullable<decimal> OLD_HINS_DAMAGE_VALUE { get; set; }
        public Nullable<decimal> NEW_HINS_DAMAGE_VALUE { get; set; }
        public string OLD_HINS_PROVINCE_CODE { get; set; }
        public string OLD_HINS_PROVINCE_NAME { get; set; }
        public string OLD_HINS_DISTRICT_CODE { get; set; }
        public string OLD_HINS_DISTRICT_NAME { get; set; }
        public string OLD_HINS_WARD_CODE { get; set; }
        public string OLD_HINS_WARD_NAME { get; set; }
        public string OLD_HINS_OWNERSHIP_NAME { get; set; }
        public string OLD_HINS_HOUSETYPE_NAME { get; set; }
        public string OLD_HINS_KINDOFHOUSE_NAME { get; set; }
        public string NEW_HINS_PROVINCE_CODE { get; set; }
        public string NEW_HINS_PROVINCE_NAME { get; set; }
        public string NEW_HINS_DISTRICT_CODE { get; set; }
        public string NEW_HINS_DISTRICT_NAME { get; set; }
        public string NEW_HINS_WARD_CODE { get; set; }
        public string NEW_HINS_WARD_NAME { get; set; }
        public string NEW_HINS_OWNERSHIP_NAME { get; set; }
        public string NEW_HINS_HOUSETYPE_NAME { get; set; }
        public string NEW_HINS_KINDOFHOUSE_NAME { get; set; }

        public string OLD_CUST_PROVINCE_NAME { get; set; }
        public string NEW_CUST_PROVINCE_NAME { get; set; }
        public string OLD_CUST_DISTRICT_NAME { get; set; }
        public string NEW_CUST_DISTRICT_NAME { get; set; }
        public string OLD_CUST_WARD_NAME { get; set; }
        public string NEW_CUST_WARD_NAME { get; set; }
        public string OLD_VEH_BRAND_NAME { get; set; }
        public string NEW_VEH_BRAND_NAME { get; set; }
        public string OLD_VEH_MODEL_NAME { get; set; }
        public string NEW_VEH_MODEL_NAME { get; set; }
        public string OLD_VEH_ORIGIN_NAME { get; set; }
        public string NEW_VEH_ORIGIN_NAME { get; set; }
        public string OLD_VEH_PURPOSE_NAME { get; set; }
        public string NEW_VEH_PURPOSE_NAME { get; set; }
        public string OLD_BILL_PROVINCE_NAME { get; set; }
        public string NEW_BILL_PROVINCE_NAME { get; set; }
        public string OLD_BILL_DISTRICT_NAME { get; set; }
        public string NEW_BILL_DISTRICT_NAME { get; set; }
        public string OLD_BILL_WARD_NAME { get; set; }
        public string NEW_BILL_WARD_NAME { get; set; }
        public List<InsuranceContractDKBSModel> OLD_DKBS_LIST { get; set; }
        public List<InsuranceContractDKBSModel> NEW_DKBS_LIST { get; set; }
        public FreightInsFeeModel OLD_VEHICLE_TYPE { get; set; }
        public FreightInsFeeModel NEW_VEHICLE_TYPE { get; set; }
        public List<InsuredPersonInfoModel> OLD_LIST_INSURED_PERSON { get; set; }
        public List<InsuredPersonInfoModel> NEW_LIST_INSURED_PERSON { get; set; }
        public List<InsuredPersonDetailModel> OLD_LIST_INSURED_PERSON_DETAIL { get; set; }
        public List<InsuredPersonDetailModel> NEW_LIST_INSURED_PERSON_DETAIL { get; set; }
    }

    public partial class ContractAlterHistory
    {
        [JsonIgnore]
        public bool IsOriginal => OLD_ALTER_TIMES == null && NEW_ALTER_TIMES == null;
        [JsonIgnore]
        public bool IsExpanded { get; set; }
        [JsonIgnore]
        public string ExpanderIcon => IsExpanded ? "icon_collapse.png" : "icon_expand.png";
        [JsonIgnore]
        public bool IsShowAllInformation { get; set; } = true;
        [JsonIgnore]
        [DependsOn("OLD_TNDS_AUTO_LOAD_OWN")]
        public string OLD_SAME_OWNER => !string.IsNullOrEmpty(OLD_TNDS_AUTO_LOAD_OWN) && OLD_TNDS_AUTO_LOAD_OWN != "0" ? AppResources.Yes : AppResources.No;
        [JsonIgnore]
        [DependsOn("NEW_TNDS_AUTO_LOAD_OWN")]
        public string NEW_SAME_OWNER => !string.IsNullOrEmpty(NEW_TNDS_AUTO_LOAD_OWN) && NEW_TNDS_AUTO_LOAD_OWN != "0" ? AppResources.Yes : AppResources.No;
        [JsonIgnore]
        [DependsOn("OLD_CONTRACT_ISSUE_TYPE", "OLD_CONTRACT_STATUS")]
        public string OLD_CONTRACT_STATUS_STRING => MobileLib.GetContractStatusString(OLD_CONTRACT_ISSUE_TYPE, OLD_CONTRACT_STATUS);
        [JsonIgnore]
        [DependsOn("NEW_CONTRACT_ISSUE_TYPE", "NEW_CONTRACT_STATUS")]
        public string NEW_CONTRACT_STATUS_STRING => MobileLib.GetContractStatusString(NEW_CONTRACT_ISSUE_TYPE, NEW_CONTRACT_STATUS);
    }
}