using System;
using System.Collections.Generic;
using System.Text;

namespace QRMS.Models
{
    public class InsuranceContractModel
    {
        public int ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> CUST_ACCOUNT_ID { get; set; }
        public string CUST_TYPE { get; set; }
        public string CUST_NAME { get; set; }
        public string IDENTITY_NO { get; set; }
        public string CUST_PHONE { get; set; }
        public string CUST_EMAIL { get; set; }
        public string CUST_ADDRESS { get; set; }
        public Nullable<int> CUST_COUNTRY_ID { get; set; }
        public Nullable<int> CUST_PROVINCE_ID { get; set; }
        public Nullable<int> CUST_DISTRICT_ID { get; set; }
        public Nullable<int> CUS_WARD_ID { get; set; }
        public string BEN_NAME { get; set; }
        public string BEN_IDENTITY_ID { get; set; }
        public string BEN_PHONE { get; set; }
        public string BILL_NAME { get; set; }
        public Nullable<int> BILL_IDENTITY_NO { get; set; }
        public Nullable<int> BILL_COUNTRY_ID { get; set; }
        public Nullable<int> BILL_PROVINCE_ID { get; set; }
        public Nullable<int> BILL_DISTRICT_ID { get; set; }
        public Nullable<int> BILL_WARD_ID { get; set; }
        public string BILL_ADDRESS { get; set; }
        public string VEH_PLATE_NO { get; set; }
        public string VEH_FRAME_NO { get; set; }
        public string VEH_ENGINE_NO { get; set; }
        public Nullable<int> VEH_BRAND_ID { get; set; }
        public Nullable<int> VEH_MODEL_ID { get; set; }
        public Nullable<int> VEH_TYPE_ID { get; set; }
        public Nullable<decimal> VEH_CUBE_CAPACITY { get; set; }
        public Nullable<decimal> VEH_MAX_LOAD { get; set; }
        public Nullable<short> VEH_SEAT_NO { get; set; }
        public Nullable<int> VEH_ORIGIN { get; set; }
        public Nullable<System.DateTime> VEH_FIRST_REG_DATE { get; set; }
        public Nullable<int> VEH_PURPOSE_ID { get; set; }
        public Nullable<decimal> VEH_VALUE { get; set; }
        public Nullable<int> SALE_AGENT_ID { get; set; }
        public string SALE_AGENT_CODE { get; set; }
        public Nullable<int> SALE_ACCOUNT_ID { get; set; }
        public string SALE_PERSONEL_CODE { get; set; }
        public string CONTRACT_CERT_NO { get; set; }
        public string CONTRACT_PRINT_NO { get; set; }
        public Nullable<System.DateTime> CONTRACT_ISSUED_DATE { get; set; }
        public Nullable<System.DateTime> CONTRACT_START_DATE { get; set; }
        public Nullable<System.DateTime> CONTRACT_EXPIRE_DATE { get; set; }
        public string CONTRACT_ISSUE_TYPE { get; set; }
        public Nullable<decimal> INSURED_TOTAL_VAL { get; set; }
        public Nullable<decimal> DEDUCT_TOTAL_VAL { get; set; }
        public Nullable<decimal> TOTAL_PRICE { get; set; }
        public Nullable<decimal> TOTAL_DEDUCT_PRICE { get; set; }
        public Nullable<decimal> TOTAL_DEDUCT_RATIO { get; set; }
        public Nullable<float> TOTAL_VAT { get; set; }
        public Nullable<int> PAY_METHOD { get; set; }
        public Nullable<System.DateTime> PAY_DUE_DATE { get; set; }
        public Nullable<decimal> TNDSBB_AUTO_PRICE { get; set; }
        public Nullable<decimal> TNDSBB_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> TNSDBB_AUTO_VAT { get; set; }
        public Nullable<decimal> TNDSBB_MOTO_PRICE { get; set; }
        public Nullable<decimal> TNDSBB_MOTO_DE_PRICE { get; set; }
        public Nullable<decimal> TNDSBB_MOTO_VAT { get; set; }
        public Nullable<short> TNVN_AUTO_CREW_NO { get; set; }
        public Nullable<int> TNVN_AUTO_CREW_PCLAIM_ID { get; set; }
        public Nullable<decimal> TNVN_AUTO_CREW_PCLAIM { get; set; }
        public Nullable<short> TNVN_AUTO_PSGR_NO { get; set; }
        public Nullable<int> TNVN_AUTO_PSGR_PCLAIM_ID { get; set; }
        public Nullable<decimal> TNVN_AUTO_PSGR_PCLAIM { get; set; }
        public Nullable<decimal> TNVN_AUTO_PRICE { get; set; }
        public Nullable<decimal> TNVN_AUTO_DE_PRICE { get; set; }
        public Nullable<float> TNVN_AUTO_DE_RATIO { get; set; }
        public Nullable<decimal> TNVN_AUTO_VAT { get; set; }
        public Nullable<int> TNDSTN_ADD_AUTO_TYPE { get; set; }
        public Nullable<int> TNDSTN_ADD_AUTO_PCLAIM_ID { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_ASSEST { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_CREW { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_PRICE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_VAT { get; set; }
        public Nullable<int> TNDSTN_ADD_AUTO_PSGR { get; set; }
        public Nullable<int> TNDS_AUTO_LOAD_TYPE { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_LMT { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_DEDUCT { get; set; }
        public string TNDS_AUTO_LOAD_OWN { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_PRICE { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_DE_PRICE { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_VAT { get; set; }
        public Nullable<decimal> VC_AUTO_VEH_VALUE { get; set; }
        public Nullable<decimal> VS_AUTO_INSURE_VAL { get; set; }
        public Nullable<decimal> VC_AUTO_CLAIM_DEDUCT { get; set; }
        public Nullable<decimal> VC_AUTO_DE_PRICE { get; set; }
        public Nullable<decimal> VC_AUTO_DE_PRICE_RATIO { get; set; }
        public Nullable<decimal> VC_AUTO_PRICE { get; set; }
        public Nullable<decimal> VC_AUTO_VAT { get; set; }
        public Nullable<int> TNVN_MOTO_PCLAIM_ID { get; set; }
        public Nullable<decimal> TNVN_MOTO_PCLAIM { get; set; }
        public Nullable<decimal> TNVN_MOTO_PRICE { get; set; }
        public Nullable<decimal> TNVN_MOTO_DE_PRICE { get; set; }
        public Nullable<decimal> TNVN_MOTO_VAT { get; set; }
        public Nullable<decimal> VC_MOTO_VEH_VALUE { get; set; }
        public Nullable<decimal> VC_MOTO_INSURE_VAL { get; set; }
        public Nullable<decimal> VC_MOTO_CLAIM_DEDUCT { get; set; }
        public Nullable<decimal> VC_MOTO_PRICE { get; set; }
        public Nullable<decimal> VC_MOTO_DE_PRICE { get; set; }
        public Nullable<decimal> VC_MOTO_DE_RATIO { get; set; }
        public Nullable<decimal> VC_MOTO_VAT { get; set; }
        public string STATUS_RECORD { get; set; }
        public Nullable<int> TNDSTN_ADD_MOTO_TYPE { get; set; }
        public Nullable<int> TNDSTN_ADD_MOTO_PCLAIM_ID { get; set; }
        public Nullable<decimal> TNDSTN_ADD_MOTO_ASSEST { get; set; }
        public Nullable<decimal> TNDSTN_ADD_MOTO_CREW { get; set; }
        public Nullable<decimal> TNDSTN_ADD_MOTO_PSGR { get; set; }
        public Nullable<decimal> TNDSTN_ADD_PRICE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_DE_PRICE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_VAT { get; set; }
        public Nullable<int> CONTRACT_STATUS { get; set; }
        public Nullable<int> INPUTING_USER_ID { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
        public Nullable<int> APPROVE_USER_ID { get; set; }
        public Nullable<System.DateTime> APPROVE_DATE { get; set; }
        public string CONTRACT_CODE { get; set; }
        public string AGENT_NAME { get; set; }
        public Nullable<int> AGENT_ID { get; set; }
        public string AGENT_CODE { get; set; }
        public Nullable<int> APPROVAL_AGENT_ID { get; set; }
        public string APPROVAL_AGENT_CODE { get; set; }
        public string APPROVAL_AGENT_NAME { get; set; }
        public Nullable<int> DIVN_ID { get; set; }
        public string DIVN_CODE { get; set; }
        public string DIVN_NAME { get; set; }
        public Nullable<int> INSUR_PRODUCT_ID { get; set; }
        public string INSUR_PRODUCT_CODE { get; set; }
        public string INSUR_PRODUCT_NAME { get; set; }
        public string TAX_NO { get; set; }
        public Nullable<int> AGENT_ID_C_1 { get; set; }
        public Nullable<int> AGENT_ID_C_2 { get; set; }
        public Nullable<int> AGENT_ID_C_3 { get; set; }
        public Nullable<int> AGENT_ID_C_4 { get; set; }
        public Nullable<int> AGENT_ID_C_5 { get; set; }
        public Nullable<int> AGENT_ID_C_6 { get; set; }
        public Nullable<int> AGENT_ID_C_7 { get; set; }
        public Nullable<int> AGENT_ID_C_8 { get; set; }
        public Nullable<int> AGENT_ID_C_9 { get; set; }
        public Nullable<int> AGENT_ID_C_10 { get; set; }
        public string SALE_ACCOUNT_CODE { get; set; }
        public string SALE_ACCOUNT_NAME { get; set; }
        public string CUST_SEX { get; set; }
        public string CUST_COUNTRY_CODE { get; set; }
        public string CUST_PROVINCE_CODE { get; set; }
        public string CUST_DISTRICT_CODE { get; set; }
        public string CUS_WARD_CODE { get; set; }
        public string VEH_BRAND_CODE { get; set; }
        public string VEH_MODEL_CODE { get; set; }
        public string VEH_TYPE_CODE { get; set; }
        public string CONTRACT_PARENTS { get; set; }
        public Nullable<decimal> TOTAL_ALTERED_PRICE { get; set; }
        public Nullable<decimal> TOTAL_FINAL_PRICE { get; set; }
        public Nullable<decimal> TNDSTN_ADD_AUTO_PCLAIM { get; set; }
        public Nullable<short> LOAD_WEIGHT { get; set; }
        public Nullable<int> TNDS_AUTO_LOAD_LVL_ID { get; set; }
        public Nullable<decimal> TNDS_AUTO_LOAD_PTON { get; set; }
        public Nullable<decimal> TNVN_AUTO_CREW_PRICE { get; set; }
        public Nullable<decimal> TNVN_AUTO_CREW_DE_PRICE { get; set; }
        public Nullable<decimal> TNVN_AUTO_CREW_VAT { get; set; }
        public Nullable<decimal> TNVN_AUTO_PSGR_PRICE { get; set; }
        public Nullable<decimal> TNVN_AUTO_PSGR_DE_PRICE { get; set; }
        public Nullable<decimal> TNVN_AUTO_PSGR_VAT { get; set; }
        public Nullable<short> ALTER_STATUS { get; set; }
        public Nullable<short> ALTER_TIMES { get; set; }

        public int PageTotal { get; set; }
    }
}
